version: "3.8"
services:
  magicmirror:
    image: bastilimbach/docker-magicmirror:latest
    container_name: magicmirror
    ports:
      - "2814:8080"
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
    user: "${MM_UID}:${MM_GID}"
    volumes:
      - ./config:/opt/magic_mirror/config  # Persistent config
      - ./custom_modules/MMM-StarTrekQuote:/opt/magic_mirror/modules/MMM-StarTrekQuote

